server:
  port: 8889

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BanuYilmazYildiz/ConfigServer.git
          default-label: main # repoyu olusturduğumuz branch
          skip-ssl-validation: true
          username: BanuYilmazYildiz
          password: ${java_11_config_server_access_token}