server:
  port: 7071

spring:
#  zipkin:
#    enabled: true
#    base-url: http://localhost:9411
#    service:
#      name: user-service
  data:
    mongodb:
      host: localhost
      port: 27020
      username: java11user #admin arayüzünü değil yeni oluşturulan userın adı. Direkt admin ile giriş yapmak tehlikeli. Giriş yapabileceği terk yer userdb.
      password: root
      datasource: userdb
  rabbitmq:
    host: localhost
    port: 5672
    username: java11
    password: 123

jwt:
  secretkey: ${socialmediaaudience}
  issuer: ${socialmediaissuer}
  audience: ${socialmediasecretkey}

rabbitmq:
  exchange-auth: auth-exchange
  register-key: register-key
  queue-register: register-queue

